language: scala
sbt_args: "-no-colors -J-Xmx2G -JXss8m"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: compile
      script:
        - sbt clean +test
    # run ci-release only if previous stages passed
    - stage: release
      script:
        - sbt ci-release
