object DijkstraExampleApp extends DijkstraExample with App
object BfsExampleApp extends BfsExample with App
object CatsExampleApp extends CatsExample with App
object CustomGraphExampleApp extends CustomGraphExample with App
object DfsExampleApp extends DfsExample with App
object GraphMLExampleApp extends GraphMLExample with App
object SimpleGraphExampleApp extends SimpleGraphExample with App
object TopologicalSortingExampleApp extends TopologicalSortingExample with App
object JsonExampleApp extends JsonExample with App